#!/bin/bash

#generate random passwords with random command

echo ${RANDOM}

password="${RANDOM}${RANDOM}${RANDOM}"
echo "the pswd by random command: ${password}"

#generate password with date command

new_pass="$(date +%s%N)"
echo "the password generated by date command: ${new_pass}"


#sha256sum and head command
#head -n filename gives n number of top lines
#head -c1 gives first character of the line
#Generating a better password
password=$(date +%s%N | sha256sum | head -c32 )
echo "${password}"

password=$(date +%s%N${RANDOM}${RANDOM} | sha256sum | head -c48)
echo "${password}"

#adding special characters to the password
special_characters=$(echo '!@#$%^&*()_-=+' | fold -w1 | shuf | head -c1 )
echo "${special_characters}"

#generating final password
echo "${password}${special_characters}"