  - name: install packages based on OS_family
    hosts: all
    become: yes
    tasks:
      - name: install packages in ubuntu
        ansible.builtin.package:
          name: apache2
          state: present
        when: ansible_os_family=="debian"

      - name: install packages in rhel
        ansible.builtin.package:
          name: httpd
          state: present
        when: ansible_os_family=="RedHat"