- name: installing service and managing it on remote server
  hosts: ec2_instance
  become: yes
  #give which service you want to install and make sure
  #the service is running
  vars_prompt:
    - name: service_name
      prompt: "enter your sevice to manage "
      private: no 
    
  tasks:
    - name: make sure the service is present
      ansible.builtin.package:
        name: "{{ service_name }}"
        state: present
      notify: Restart service

    - name: make sure the service is started and running
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
  handlers:
  - name: Restart service
    ansible.builtin.service:
      name: "{{ service_name }}"
      state: restarted